### ISSUE TITLE
前端优化（页面问题及API请求路径）-1124

### ISSUE THREAD

**Issue by guan2w** [shanghairanking/uic-web#2]
#### 在页面尺寸比较小的情况下
- [ ] 页面左侧的4步骤区域，没有垂直居中；
- [ ] 持续将页面下滑，页面底部会出现白色区域。

### API 请求路径优化
- 为了保证各个项目在请求 API 时，有更加统一的路径格式，以降低线上部署的复杂度，和以后排查请求相关问题的难度，需要对本项目的 API 请求路径做出以下调整
    - [ ] 之前请求后端 API 时，使用的前缀是`/v1/`，现在需要改为`/bkxx/api/v1/`
- 以后的前端项目请求 API 时，应该使用统一形式`/项目名/api/版本/`
    - 当项目部署在根路径时，会简化为`/api/版本/`

**Comment by yyqxjwxy** [comment]
### 问题1：页面左侧的4步骤区域，没有垂直居中
  - 解决办法
    - 使用绝对定位的css3 transfom，translate设置水平垂直居中

###  问题2：持续将页面下滑，页面底部会出现白色区域
  - 解决办法
    - 因为步骤条的高度固定所以设置媒体查询使其在不同的分辨率下动态改变高度防止在屏幕高度低的时候因为步骤条太高页面出现滚动条出现白条


### 问题3：API 请求路径优化
  - 解决办法
    - 通过在环境配置文件中添加一个固定的变量，在请求接口文件中开启baseUrl通过判断不同的开发环境在请求接口动态添加这个变量
